let books = [
    {
        name: "Thirukkural",
        author: "Thiruvalluvar",
        dateAdded: "18/5/2023",
        image: "./assets/thiru.jpeg",
        price: 90,
        contact: "+91 9812378877",
        tags: ["knowledge"],
    },
    {
        name: "Wings of Fire",
        author: "Dr.A.P.J.Abdul Kalam",
        dateAdded: "18/5/2023",
        image: "./assets/wing.jpg",
        price: 180,
        contact: "+91 981237887",
        tags: ["biography, knowledge", "motivation"],
    },
    {
        name: "Kingdom of Shiva",
        author: "Sivkishen",
        dateAdded: "18/5/2023",
        image: "./assets/shiv.webp",
        price: 220,
        contact: "+91 9812378877",
        tags: ["biography", "knowledge", "religion"],
    },
    {
        name: "Mahabharatha",
        author: "Krishna Dharma",
        dateAdded: "18/5/2023",
        image: "./assets/maha.jpeg",
        price: 220,
        contact: "+91 9812378877",
        tags: ["biography", "knowledge", "religion"],
    },
    {
        name: "Dune",
        author: "Frank Herbert",
        dateAdded: "18/5/2023",
        image: "./assets/dune.jpg",
        price: 300,
        contact: "+91 9812378877",
        tags: ["novel"],
    },
    {
        name: "Ikigai",
        author: "Hector Garcia",
        dateAdded: "18/5/2023",
        image: "./assets/ikigai.jpg",
        price: 300,
        contact: "+91 9812378877",
        tags: ["life"],
    },
    {
        name: "Rich Dad, Poor Dad",
        author: "Robert Kiyosaki",
        dateAdded: "18/5/2023",
        image: "./assets/rich.jpeg",
        price: 200,
        contact: "+91 9812378877",
        tags: ["life"],
    },
    {
        name: "Atomic Habits",
        author: "James Clear",
        dateAdded: "18/5/2023",
        image: "./assets/atom.jpeg",
        price: 340,
        contact: "+91 9812378877",
        tags: ["life"],
    },
    {
        name: "The Big Sleep",
        author: "Raymond Chandler",
        dateAdded: "18/5/2023",
        image: "./assets/bigsleep.jpeg",
        price: 190,
        contact: "+91 9812378877",
        tags: ["novel"],
    },

];
